name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends -y build-essential gcc-multilib g++-multilib git patch wget cpio file bc

    - name: Cache downloads
      uses: actions/cache@v2
      with:
        path: dl
        key: buildroot-dl

    - name: Build the package
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: '*.ipk'
